#!/usr/bin/env python3
import argparse
import json
import re
import sys
from pathlib import Path

TECH_CANONICAL = {
    'graphql': 'GraphQL', 'kubernetes': 'Kubernetes', 'aws': 'AWS', 'azure': 'Azure', 'gcp': 'GCP',
    'eks': 'EKS', 'aks': 'AKS', 'rest api': 'REST API', 'mcp': 'MCP', 'yaml': 'YAML', 'json': 'JSON',
    'ci/cd': 'CI/CD', 'iac': 'IaC', 'mlops': 'MLOps', 'opa': 'OPA', 'terraform': 'Terraform'
}

def load_json(path):
    with open(path, 'r', encoding='utf-8') as f:
        return json.load(f)

def words(s):
    return re.findall(r"[A-Za-z0-9+/.-]+", s or '')

def all_labels(spec):
    labels = [spec.get('title',''), spec.get('subtitle',''), spec.get('footer','')]
    labels.append(spec.get('business_outcome_description',''))
    for lane in spec.get('lanes', []):
        labels.append(lane.get('title',''))
        labels.extend(lane.get('items', []))
    for zone in spec.get('zones', []):
        labels.append(zone.get('title',''))
        labels.append(zone.get('subtitle',''))
        labels.extend(zone.get('items', []))
        for child in zone.get('children', []):
            labels.append(child.get('title',''))
            labels.extend(child.get('items', []))
    labels.extend(spec.get('operations', []))
    for flow in spec.get('flows', []):
        labels.append(flow.get('label',''))
    return [x for x in labels if x]

def main():
    ap = argparse.ArgumentParser(description='Runtime guardrail validator for architecture specs; no report file is generated by default.')
    ap.add_argument('--input', required=True)
    ap.add_argument('--quiet', action='store_true')
    ap.add_argument('--strict', action='store_true')
    args = ap.parse_args()

    spec = load_json(Path(args.input))
    issues = []
    labels = all_labels(spec)

    for label in labels:
        if len(label) > 70:
            issues.append(f'Long label may not fit cleanly: {label[:90]}')
        if len(words(label)) > 10 and label not in [spec.get('subtitle',''), spec.get('business_outcome_description','')]:
            issues.append(f'Box label has too many words: {label[:90]}')

    bod = spec.get('business_outcome_description','')
    wc = len(words(bod))
    if not bod:
        issues.append('Missing business_outcome_description for CIO-ready overview.')
    elif wc < 12 or wc > 55:
        issues.append(f'business_outcome_description should be brief but meaningful; current words={wc}.')

    joined = ' '.join(labels)
    for lower, canonical in TECH_CANONICAL.items():
        if re.search(re.escape(canonical), joined, re.I) and canonical not in joined:
            issues.append(f'Canonical spelling should be {canonical}.')

    for zone in spec.get('zones', []):
        if len(zone.get('items', [])) > 5 and not zone.get('expand', False):
            issues.append(f'Zone with many items should be marked expand=true: {zone.get("title")}')

    if not args.quiet:
        if issues:
            print('Guardrail warnings:')
            for i in issues:
                print('-', i)
        else:
            print('Guardrails passed.')

    if args.strict and issues:
        sys.exit(1)

if __name__ == '__main__':
    main()
